platform :ios, '11.0'

def shared_pods
  use_frameworks!
  pod 'FitAnalytics-WebWidget', :path => '../../'
  pod "PromiseKit", "~> 6.0"
end

target 'TestRunner' do
  shared_pods
end

target 'WidgetTests' do
  shared_pods
end

target 'ReporterTests' do
  shared_pods
end

target 'ReporterSwiftTests' do
  shared_pods
end
