platform :ios, '8.0'

def shared_pods
  use_frameworks!
  pod 'FitAnalytics-WebWidget', :path => '../../FitAnalytics-WebWidget'
  pod "PromiseKit", "~> 4.0"
end

target 'TestRunner' do
  shared_pods
end

target 'WidgetTests' do
  shared_pods
end

target 'ReporterTests' do
  shared_pods
end
