platform :ios, '11.0'

def shared_pods
  pod 'FitAnalytics-WebWidget', :path => '../../'
  pod 'PromiseKit', '~> 8.0'
end

target 'TestRunner' do
  shared_pods
end

target 'WidgetTests' do
  shared_pods
end

target 'ReporterTests' do
  shared_pods
end

target 'ReporterSwiftTests' do
  shared_pods
end
